### ISSUE TITLE
Create Readme

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/proton-local#2]
Lets document how to use this tool with a nice readme file

**Comment by xavier506** [comment]
@leisterfrancisco  we need to add the proton testnet logo instead of lacchain 

![image](https://user-images.githubusercontent.com/5632966/125024452-0ae05400-e03e-11eb-833c-c8e79f85ddce.png)


please see this readme file as an example

**Comment by leisterfrancisco** [comment]
Solved by https://github.com/eoscostarica/proton-local/pull/5

**Comment by leisterfrancisco** [comment]
Solved by #5
